# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14wzGaYVgyaorVEq5IXvjRp9qLwdiRgwU
"""

import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from textblob import TextBlob
from collections import Counter
import numpy as np

nltk.download('stopwords')
nltk.download('punkt')

file_path = '/content/reviews.txt'
with open(file_path, 'r', encoding='utf-8') as file:
    reviews = file.readlines()

def clean_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)  # Remove special characters
    text = ' '.join([word for word in text.split() if word not in stopwords.words('english')])  # Remove stopwords
    return text

cleaned_reviews = [clean_text(review) for review in reviews]

def get_sentiment(text):
    return TextBlob(text).sentiment.polarity

sentiments = [get_sentiment(review) for review in cleaned_reviews]

df = pd.DataFrame({'Review': reviews, 'Cleaned_Review': cleaned_reviews, 'Sentiment': sentiments})

conditions = [
    (df['Sentiment'] > 0),
    (df['Sentiment'] == 0),
    (df['Sentiment'] < 0)
]
choices = ['Positive', 'Neutral', 'Negative']
df['Sentiment_Label'] = np.select(conditions, choices)

top_reviews = df.loc[df['Sentiment'].abs().nlargest(5).index, ['Review', 'Sentiment_Label']]

print("Top 5 Reviews:")
print(top_reviews)